### PR TITLE
Removing equinox experimental

### LINKED ISSUE #70: BatchNorm is no longer experimental
Hi everyone!

I installed the latest EqxVision and got an import error when importing `equinox.experimental`. This seems to be because Equinox _graduated_ BatchNorm to stable on [v0.10.3](https://github.com/patrick-kidger/equinox/releases/tag/v0.10.3). 

I'll create a short PR for this.

### PR DESCRIPTION
**Pull request by stepp1**
This PR updates Equinox BatchNorm as it's no longer an experimental feat.

Fixes #70

### CODE REVIEW

**Comment by paganpasta** [comment]
Thanks for the PR! 
It seems that few pre-commit checks are failing. Let me know if you will be able to fix and push them. 
Else, I'll try to pick this up as soon as I can.

**Comment by stepp1** [comment]
Hi there!
There were other ways of calling BatchNorm that I didn't catch at first, so I updated the PR. Now, when running the precommit hook, everything seems ok.

However, I'm getting a bunch of errors (100%!) when running pytest.

**Comment by paganpasta** [comment]
Ok, I'll take a look at as to why they might be failing.

**Comment by stepp1** [comment]
Hi there! I was looking through the errors, and the culprit might be the changes in how the stateful ops are handled now. 
I'm not very familiar w/ equinox, but I'll keep looking.

Edit: I think I narrowed it down to the fact that the new BatchNorm __call__ breaks inside a ConvNormActivation. This occurs because the method now requires both `x` **and** `state` when called. Maybe @patrick-kidger can help here

**Comment by patrick-kidger** [comment]
The new `BatchNorm` has a different API to the previous experimental version. (Incidentally the other normalisation layers -- `LayerNorm`, `GroupNorm` -- also support this new API if needed, so they are interchangeable.)

It should be called as `output, state = norm_layer(input, state)`, see the [stateful tutorial](https://docs.kidger.site/equinox/examples/stateful/).

I think this should be straightforward enough -- simply thread the additional state through.

**Pull request merged**
